# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-09 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('photo_url', models.URLField()),
                ('party_profile_url', models.URLField()),
                ('website_url', models.URLField()),
                ('twitter_url', models.URLField()),
                ('facebook_url', models.URLField()),
                ('instagram_url', models.URLField()),
                ('linkedin_url', models.URLField()),
                ('youtube_url', models.URLField()),
                ('snapchat_url', models.URLField()),
                ('phone_1', models.CharField(max_length=30)),
                ('phone_2', models.CharField(max_length=30)),
                ('constituency', models.CharField(max_length=30)),
                ('party', models.CharField(max_length=30)),
                ('slug', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RssStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('negative', models.IntegerField()),
                ('positive', models.IntegerField()),
                ('neutral', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('total_negative', models.IntegerField()),
                ('total_positive', models.IntegerField()),
                ('total_neutral', models.IntegerField()),
                ('rss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampleapp.RssStats')),
            ],
        ),
        migrations.CreateModel(
            name='TwitterStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('negative', models.IntegerField()),
                ('positive', models.IntegerField()),
                ('neutral', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='stats',
            name='twitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampleapp.TwitterStats'),
        ),
        migrations.AddField(
            model_name='politician',
            name='stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampleapp.Stats'),
        ),
    ]
