# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-09 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0004_auto_20160709_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politician',
            name='email',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='phone_1',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='phone_2',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
