# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-09 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0008_auto_20160709_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssstats',
            name='negative',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rssstats',
            name='neutral',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rssstats',
            name='positive',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rssstats',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='total_negative',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='total_neutral',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stats',
            name='total_positive',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='twitterstats',
            name='negative',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='twitterstats',
            name='neutral',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='twitterstats',
            name='positive',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='twitterstats',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
