# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-09 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0009_auto_20160709_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='rss',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sampleapp.RssStats'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='twitter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sampleapp.TwitterStats'),
        ),
    ]
